### ISSUE TITLE
[BUG?] Heartbeat on non running activity

### ISSUE THREAD

**Issue by Zylius** [temporalio/roadrunner-temporal#109]
### Describe the bug

Sending out a heartbeat in activity method results in  `heartbeat on non running activity` (at random times). The failed state for heartbeats seems to be set upon roadrunner launch (`rr serve` command). If the activity worker launches with a 'failed' heartbeat state, it'll continue failing upon Heartbeats until it, or the Workflows `rr serve` instance is killed and restarted. I'm still not very clear on what fixes it. The more roadrunner instances I run (`rr serve`)  the higher the chance of this error.

The failing heartbeats  throw: `'activity_pool_get_activity_context: heartbeat on non running activity' on tcp://127.0.0.1:6001 `

Or sometimes the worker (very rarely) enters a different state for heartbeats and failed with a socket error. IDK if it's related: 
`socket_send(): unable to write to socket [32]: Broken pipe `

### To Reproduce

1. Create a dummy workflow.
2. Create a dummy activity.
3. Send a heartbeat in the activity
4. Launch `rr serve` commands for the workflow part and activities separately. In our system workflows are contained in a single app, and activities are handled by different service apps. The more `rr serve` instances for the activity app is launched, the higher the chance one will see the error. It's pretty easy to recreate, it doesn't require many workers. I would say on my end with one worker it's about 50/50 to see the heartbeat error.
5. Launch the workflow
6. See the error.

### Expected behavior

Heartbeat to be sent out successfully. 

#### Errors

```
Temporal\Exception\TransportException: Error 'activity_pool_get_activity_context: heartbeat on non running activity' on tcp://127.0.0.1:6001 
Spiral\Goridge\RPC\Exception\ServiceException: Error 'activity_pool_get_activity_context: heartbeat on non running activity' on tcp://127.0.0.1:6001 in /home/docker/services/hyperwallet/vendor/spiral/goridge/src/RPC/RPC.php:128
Stack trace:
#0 /home/docker/services/hyperwallet/vendor/spiral/goridge/src/RPC/RPC.php(98): Spiral\Goridge\RPC\RPC->decodeResponse(Object(Spiral\Goridge\Frame), NULL)
#1 /home/docker/services/hyperwallet/vendor/temporal/sdk/src/Worker/Transport/Goridge.php(56): Spiral\Goridge\RPC\RPC->call('activities.Reco...', Array)
#2 /home/docker/services/hyperwallet/vendor/temporal/sdk/src/Internal/Activity/ActivityContext.php(137): Temporal\Worker\Transport\Goridge->call('activities.Reco...', Array)
```

Very rare (dunno if related)

```
ErrorException: Warning: socket_send(): unable to write to socket [32]: Broken pipe 
ErrorException: Warning: socket_send(): unable to write to socket [32]: Broken pipe in /home/docker/services/hyperwallet/vendor/spiral/goridge/src/SocketRelay.php:234
Stack trace:
#0 /home/docker/services/hyperwallet/vendor/spiral/goridge/src/RPC/RPC.php(83): Spiral\Goridge\SocketRelay->send(Object(Spiral\Goridge\Frame))
#1 /home/docker/services/hyperwallet/vendor/temporal/sdk/src/Worker/Transport/Goridge.php(56): Spiral\Goridge\RPC\RPC->call('activities.Reco...', Array)
#2 /home/docker/services/hyperwallet/vendor/temporal/sdk/src/Internal/Activity/ActivityContext.php(137): Temporal\Worker\Transport\Goridge->call('activities.Reco...', Array)
```

#### Code samples:

```php
<?php
declare(strict_types=1);

namespace App\Command;

use Carbon\CarbonInterval;
use Temporal\Activity\ActivityOptions;
use Temporal\Workflow;
use Temporal\Workflow\WorkflowInterface;

#[WorkflowInterface]
class TemporalTestWorkflow
{
    #[Workflow\WorkflowMethod]
    public function launchActivity()
    {
        $options = ActivityOptions::new()
            ->withStartToCloseTimeout(CarbonInterval::seconds(2))
            ->withTaskQueue('hyperwallet_command_bus');

        Workflow::newUntypedActivityStub($options)->execute('testActivity');
    }
}
```

```php
<?php

declare(strict_types=1);

namespace App;

use Temporal\Activity;
use Temporal\Activity\ActivityInterface;
use Temporal\Activity\ActivityMethod;

#[ActivityInterface]
class TestActivity
{
    #[ActivityMethod]
    public function testActivity()
    {
        Activity::heartbeat('test'); // This causes failure.
    }
}
```
### Versions

- OS: In Docker `Debian GNU/Linux 10 (buster)`, host  `Pop!_OS 21.04`
- Temporal Version: 1.12.2
- Roadrunner version: 2.5.2
- PHP composer versions:
  - spiral/roadrunner: 2.5.0             
  - spiral/roadrunner-cli: 2.0.11
  - spiral/roadrunner-http: 2.0.4
  - spiral/roadrunner-worker: 2.1.3
  - temporal/sdk: 1.0.4
- We're using docker image `temporalio/auto-setup` in our `docker-compose.yaml`, we've seen this error with sample temporal `docker-compose-mysql-es.yaml` files as well.

### Additional context

I'm not sure, maybe this is an issue only with our setup, but any help would be greatly appreciated.

**Comment by Zylius** [comment]
Hello, any news on this? :eyes:

**Comment by rustatian** [comment]
@Zylius Sorry, I got sick 😢

**Comment by Zylius** [comment]
Ahh the season of the year, wish you get well soon!!!

**Comment by rustatian** [comment]
@Zylius Ok 😃 Sorry for the delay (COVID-19). At the moment I'm waiting for the temporal/sdk 1.11 fix https://github.com/spiral/roadrunner-plugins/issues/12#issuecomment-972003857. After that, I'll be able to release a beta version which you can test for the heartbeats.

**Comment by Zylius** [comment]
Thanks man, happy you got better!

**Comment by rustatian** [comment]
@Zylius I forked (temporarily) the temporal/go-sdk and excluded commit with the problem. I'll release RR v2.6.0-rc.1 tomorrow, so, you can test it.

**Comment by Zylius** [comment]
WIll be ready to test it! :grin:

**Comment by rustatian** [comment]
@Zylius here you are: https://github.com/spiral/roadrunner-binary/releases/tag/v2.6.0-rc.1

**Comment by Zylius** [comment]
Ahh snap, still getting it. 
```
2021-11-26T11:20:33.778Z	ERROR	temporal    	Activity error.	{"Namespace": "default", "TaskQueue": "test_command_bus", "WorkerID": "6668@64ddfa348084@test_command_bus@2", "WorkflowID": "20c0e906-feb7-419d-95a8-690ec59bd64a", "RunID": "7f727c43-dba8-4df9-a05d-f462ddf67ba6", "ActivityType": "CreateTestCommand", "Attempt": 1, "Error": "Error 'activity_pool_get_activity_context: heartbeat on non running activity' on tcp://127.0.0.1:6001 (type: Temporal\\Exception\\TransportException, retryable: true): Error 'activity_pool_get_activity_context: heartbeat on non running activity' on tcp://127.0.0.1:6001 (type: Spiral\\Goridge\\RPC\\Exception\\ServiceException, retryable: true)"}
```

Road runner version:
```
docker@64ddfa348084:~/services/test$ ./rr --version
rr version 2.6.0-rc-1 (build time: 2021-11-26T08:53:07+0000, go1.17.2)
```


Dunno maybe it's an isolated issue in our environment?
It seems no one else is reporting such issues.

**Comment by rustatian** [comment]
This is the regular issue, not the bug. The activity you are trying to ping is not running at that moment.

**Comment by rustatian** [comment]
This is not a critical error, you should treat this as a let's say, expected error when you are trying to check the HeartBeat. Because event the temporal go-sdk will return an error in that case.

**Comment by Zylius** [comment]
I'm confused, the activity is sending the heart beat in it's own code, like in  this example I gave
```
#[ActivityInterface]
class TestActivity
{
    #[ActivityMethod]
    public function testActivity()
    {
        Activity::heartbeat('test'); // This causes failure.
    }
}
```
How could the Activity `testActivity` not be running while we send out heartbeat in the `testActivity` code?
This is original error I opened this issue with.

**Comment by rustatian** [comment]
Yep, I was ill when we discussed this issue, and didn't pay enough attention to it, sorry. The activity you showed here pinging the temporal server for the heartbeat. But the heartbeat in the issue pings this `testActivity` for the heartbeat. `testActivity` after its heartbeat ends and you are trying to ping the `testActivity` after it ends.

**Comment by Zylius** [comment]
So you're saying 

```php
#[ActivityInterface]
class TestActivity
{
    #[ActivityMethod]
    public function testActivity()
    {
        Activity::heartbeat('test'); // This causes failure, cause it's sent somehow async? And when temporal gets the request for heartbeat the activity is already closed?
    }
}
```

I tried this 

```php
#[ActivityInterface]
class TestActivity
{
    #[ActivityMethod]
    public function testActivity()
    {
        Activity::heartbeat('test'); 
       /// one second sleep so activity is surely not over when temporal gets the heart beat
        sleep(1);
    }
}
```
Still the error.

Now I'm all confused about the concept of heartbeats

**Comment by rustatian** [comment]
You may have a look at our tests, where we have samples with heartbeats -> https://github.com/temporalio/roadrunner-temporal/blob/master/tests/src/Workflow/SimpleHeartbeatWorkflow.php
and the second: https://github.com/temporalio/roadrunner-temporal/blob/master/tests/src/Activity/HeartBeatActivity.php

**Comment by Zylius** [comment]
That's the issue. The test code is the same I use as an example here and the same I used to test the new rc-1. it throws me the `heartbeat on non running activity` error. Well I guess I'll try to avoid heartbeats on PHP for now.

**Comment by rustatian** [comment]
In your sample, you have only 1 ping to the temporal server and then sleep, you may try to use the loop with the heartbeats like shown in the docs: https://docs.temporal.io/docs/php/activities/#activity-heart-beating without sleep.
I'm not a PHP dev, sorry, I can't help a lot with a PHP (
You may ask for help (about how to correctly write the heartbeats) in our discord server in the temporal channel: https://discord.gg/TFeEmCs

**Comment by rustatian** [comment]
Also, make sure to set the `ActivityOptions::new()->withStartToCloseTimeout(50)` option in your workflow.

**Comment by Zylius** [comment]
Thank you very much! I'll try everything you've said :) You've been a great help. I'll report here if I find where I screwed up!

**Comment by wolfy-j** [comment]
Is there a reason why you don't have `yield` in your workflow?

**Comment by Zylius** [comment]
Weird, I think the yield makes it rarer, but I still can recreate it after a couple of roadrunner restarts and workflow relaunches.

```
2021-12-02T14:07:43.827Z	DEBUG	temporal    	ExecuteActivity	{"Namespace": "default", "TaskQueue": "saga_command_bus", "WorkerID": "5391@64ddfa348084@saga_command_bus@1", "WorkflowType": "TestWorkflow", "WorkflowID": "fdbbd843-3dc6-40f8-a84d-c2c4c04c9088", "RunID": "ec7e703a-736d-45ae-a2e6-d41e7f53ad60", "Attempt": 1, "ActivityID": "5", "ActivityType": "testActivity"}
2021-12-02T14:07:46.282Z	DEBUG	temporal    	ExecuteActivity	{"Namespace": "default", "TaskQueue": "saga_command_bus", "WorkerID": "5391@64ddfa348084@saga_command_bus@1", "WorkflowType": "TestWorkflow", "WorkflowID": "f80698b0-82e2-4452-9194-19444ba301aa", "RunID": "b4348441-c08b-4a12-8f49-126f64eeeab3", "Attempt": 1, "ActivityID": "5", "ActivityType": "testActivity"}
2021-12-02T14:07:48.254Z	DEBUG	temporal    	ExecuteActivity	{"Namespace": "default", "TaskQueue": "saga_command_bus", "WorkerID": "5391@64ddfa348084@saga_command_bus@1", "WorkflowType": "TestWorkflow", "WorkflowID": "091757be-a5aa-4a5c-8e71-4d4684759f67", "RunID": "cd615364-0d65-4b7c-aa5d-eb25c40cf9ca", "Attempt": 1, "ActivityID": "5", "ActivityType": "testActivity"}
2021-12-02T14:07:48.325Z	ERROR	temporal    	Activity error.	{"Namespace": "default", "TaskQueue": "internal_saga_queue", "WorkerID": "5391@64ddfa348084@internal_saga_queue@4", "WorkflowID": "091757be-a5aa-4a5c-8e71-4d4684759f67", "RunID": "cd615364-0d65-4b7c-aa5d-eb25c40cf9ca", "ActivityType": "testActivity", "Attempt": 1, "Error": "Error 'activity_pool_get_activity_context: heartbeat on non running activity' on tcp://127.0.0.1:6001 (type: Temporal\\Exception\\TransportException, retryable: true): Error 'activity_pool_get_activity_context: heartbeat on non running activity' on tcp://127.0.0.1:6001 (type: Spiral\\Goridge\\RPC\\Exception\\ServiceException, retryable: true)"}
```

**Comment by wolfy-j** [comment]
Responded at the forum... I'm not able to reproduce this error. Can we try to dig deeper into other issues you having "broken pipe" and etc? I wonder if we are chasing the wrong bug.

**Comment by rustatian** [comment]
The broker pipe issue might be because of RPC plugin started before the activity RPC layer. The issue was fixed in the latest version. @Zylius Could you please retest the issue on this version -> https://github.com/spiral/roadrunner-binary/releases/tag/v2.6.3?

**Comment by Zylius** [comment]
Guys, just tried it with the v2.6.3, neither with the `yield` nor without it can I reproduce the issue. I don't get the `broken pipe`, nor the `heartbeat on non running activity` anymore! I think it's fixed! Thank you so much you're great. Tried it on different queues etc. 

:bow: Thanks
