### ISSUE TITLE
[🐛 BUG]: Metric `temporal_activity_schedule_to_start_latency` useless with RR?

### ISSUE THREAD

**Issue by Zylius** [temporalio/roadrunner-temporal#183]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hey guys, need help with autoscaling roadrunner instances. I'm not sure if this is a bug, maybe there's a way around it.

I'm trying to attach HPA on kubernetes to a temporal metric, but the one which is supposed to approximate the number in the queue always stays the same. I'm guessing this is because roadrunner gets the message from temporal, which fires the `temporal_activity_schedule_to_start_latency`  and then looks for a worker. If it cannot find a free worker it then throws 

```
Error: activity_pool_execute_activity: NoFreeWorkers:
	codec_execute:
	static_pool_exec:
	static_pool_exec:
	worker_watcher_get_free_worker:
	context deadline exceeded
```	
This is exactly what we get on some of our pods, when the load increases. The workers are I/O bound so we cannot use CPU metrics to scale. Yet the 	`temporal_activity_schedule_to_start_latency` doesn't change at all, even when the roadrunner cannot find any workers and times out after  60s (default setting).

Any ideas? Maybe there are other metrics roadrunner itself can emit f.e. how long it takes to find a worker I'm not aware of?

### Version

2.7.9

**Comment by rustatian** [comment]
Hey @Zylius. You may try to increase the number of the `activity` workers, since you have I/O bound operations, you may use a fairly big number of workers.

**Comment by Zylius** [comment]
I'm already doing that, got like 50 workers. One minute we get 5000 messages the other it might be 500000, and we can't really afford to pay for all that memory all the time :/

**Comment by rustatian** [comment]
Might be increase the default timeout

**Comment by rustatian** [comment]
> Any ideas? Maybe there are other metrics roadrunner itself can emit f.e. how long it takes to find a worker I'm not aware of?

We have the queue_size metrics for the `http` plugin. I guess we need to add the same to our temporal plugin.

**Comment by rustatian** [comment]
Yeah, I guess you would be able to make a decision based on the `queue_size`, for example, if the queue_size > 1000 -> add one more RR instance.

**Comment by rustatian** [comment]
@Zylius Hey. I've added 2 new metrics - `rr_activities_pool_queue_size` and `rr_workflows_pool_queue_size`. They show the number of activities/workflows waiting for the worker.

**Comment by Zylius** [comment]
Thanks man, just wanted to say thanks for all the quick help you've been providing throughout our journey to getting a big project switched over to temporal/roadrunner. :bow: 

This will get automatically included in the next roadrunner release, right?

**Comment by rustatian** [comment]
> Thanks man, just wanted to say thanks for all the quick help you've been providing throughout our journey to getting a big project switched over to temporal/roadrunner. bow

You are very welcome my friend 🤝 

Yeah, I'll release a beta on Monday (21 of Feb) and if everything will be fine, then I'll release a 2.8.1. Will be waiting for your feedback 😃

**Comment by rustatian** [comment]
@Zylius Here you are: https://github.com/roadrunner-server/roadrunner/releases/tag/v2.8.1 😃

**Comment by Zylius** [comment]
> @Zylius Here you are: https://github.com/roadrunner-server/roadrunner/releases/tag/v2.8.1 smiley

THanks man, upgrading my configs and will let you know what I see ;)

**Comment by Zylius** [comment]
Hey @rustatian I can confirm everything is working as expected and we're receiving the values we need for scaling. Thanks !! :)

**Comment by rustatian** [comment]
Nnnnnnice 🚀
