### ISSUE TITLE
[🐛 BUG?]: MaxConcurrentActivityExecutionSize ignored.  

### ISSUE THREAD

**Issue by Zylius** [temporalio/roadrunner-temporal#193]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

MaxConcurrentActivityExecutionSize seems to be ignored, it's supposed to decrease the https://docs.temporal.io/docs/operation/how-to-tune-workers/#metrics [task_slots_available](https://docs.temporal.io/docs/operation/how-to-tune-workers/#metrics) metric, but it doesn't. On go SDK it's working.

In both go workers and PHP workers the default is 1000, but if I set it to 1 on PHP the metric stays 1000, when I set it to 1 on pure GO worker, it goes to 1 as it should.

I'm sure from the logs, RR is getting the right value. 

Any ideas guys? Maybe I'm setting up something wrong? :thinking: 

### Version

2.8.4

### Relevant log output

```shell
2022-03-22T19:12:33.968Z	DEBUG	temporal    	received message	{"data": "\n\ufffd&*\ufffd&\n\ufffd\r\n\u0016\n\u0008encoding\u0012\njson/plain\u0012\ufffd\u000c{\"TaskQueue\":\"test_queue\",\"Options\":{\"MaxConcurrentActivityExecutionSize\":1,\
"WorkerActivitiesPerSecond\":0.0,\"MaxConcurrentLocalActivityExecutionSize\":0,\"WorkerLocalActivitiesPerSecond\":0.0,\"TaskQueueActivitiesPerSecond\":0.0,\"MaxConcurrentActivityTaskPollers\":0,\"MaxConcurrentWorkflowTaskExecutionSize\":0,\"MaxConcurrentWorkflowTaskPollers\":0,\"StickyScheduleToStartTimeout\":null,\"WorkerStopTimeout\":null,\"EnableSessionWorker\":false,\"SessionResourceID\":null,\"MaxConcurrentSessionExecutionSize\":1000},\"Workflows\":[....]
{\"TaskQueue\":\"test_conversion\",\"Options\":{\"MaxConcurrentActivityExecutionSize\":1,\
"WorkerActivitiesPerSecond\":0.0,\"MaxConcurrentLocalActivityExecutionSize\":0,\"WorkerLocalActivitiesPerSecond\":0.0,\"TaskQueueActivitiesPerSecond\":0.0,\"MaxConcurrentActivityTaskPollers\":0,\"MaxConcurrentWorkflowTaskExecutionSize\":0,\"MaxConcurrentWorkflowTaskPollers\":0,\"StickyScheduleToStartTimeout\":null,\"WorkerStopTimeout\":null,\"EnableSessionWorker\":false,\"SessionResourceID\":null,\"MaxConcurrentSessionExecutionSize\":1000},\"Workflows\":[{\"Name\":\"ConverterWorkflow\",\"Queries\":[],\"Signals\":[]}],\"Activities\":[....]
```

**Comment by rustatian** [comment]
Hey @Zylius 👋🏻 . I'll verify and fix it in the next release.

**Comment by rustatian** [comment]
Hey @Zylius. I tried to verify that, but as far as I see, I definitely can manipulate this argument:
![image](https://user-images.githubusercontent.com/8040338/162772150-83af39ff-c0ff-4978-82de-495ca75ee0a4.png)
PHP side:
![image](https://user-images.githubusercontent.com/8040338/162772211-99531f19-a645-4c40-84bd-10019b51fe6b.png)

As you may see on the first screenshot, the `ActivityExecutionSize` is 10 as I set and `WorkflowTaskExecutionSize` because 1 WF was in progress to grab the metric.

**Comment by rustatian** [comment]
It would be best to wait for a little because this is not an immediate metric.

**Comment by Zylius** [comment]
Hmm I'll try to do it just like you did, maybe my code was wrong :thinking:

**Comment by Zylius** [comment]
I can confirm this was an issue on our end :( terribly sorry, closing the issue.
