### ISSUE TITLE
[💡 FEATURE REQUEST]: Overwrite `client-name` and `client-version` in Go client to represent PHP-SDK

### ISSUE THREAD

**Issue by wolfy-j** [temporalio/roadrunner-temporal#253]
In order to track the temporal usage all the client calls, workflow and activity polling calls, must container an SDK version header. Since Golang SDK represents PHP one - we have to adjust this header as well, via GRPC interceptor or another way.

See: https://github.com/temporalio/sdk-php/issues/220
Also: https://github.com/temporalio/sdk-php/blob/master/src/Client/GRPC/Context.php#L35

Target: https://github.com/temporalio/roadrunner-temporal/blob/master/plugin.go#L159

**Comment by rustatian** [comment]
Planned for the `1.5.x` temporal milestone and RR `2.11.x` version.

**Comment by rustatian** [comment]
todo: apply grpc interceptor for the worker's `ConnectionOptions`: https://pkg.go.dev/go.temporal.io/sdk@v1.15.0/internal#ConnectionOptions

**Comment by rustatian** [comment]
@wolfy-j, I'll move this ticket to the RR main repo and our issue tracker if you don't mind.
ref: https://github.com/roadrunner-server/roadrunner/issues/1249
