### ISSUE TITLE
[💡 FEATURE REQUEST]: Support FailureConverter API

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/roadrunner-temporal#277]
### I have an idea!

The error conversion API has been refactored to expose a customization point for users to control how errors are serialized/deserialized. Should start using and add support for this new API.

See also:
https://github.com/temporalio/sdk-go/pull/924
https://github.com/temporalio/sdk-typescript/pull/887
https://github.com/temporalio/api/blob/master/temporal/api/failure/v1/message.proto#L81

**Comment by cretz** [comment]
Note that at the least, `internalbindings.ConvertErrorToFailure` and `internalbindings.ConvertFailureToError` is going away next version and you'll have to call `temporal.GetDefaultFailureConverter().ErrorToFailure` and `temporal.GetDefaultFailureConverter().FailureToError` respectively to get today's behavior.

**Comment by rustatian** [comment]
Hey @cretz @Quinn-With-Two-Ns 👋🏻 
Nice, thanks for noting; we'll plan this for the RoadRunner `v2.12.0`.
