### ISSUE TITLE
[💡 FEATURE REQUEST]: Typed Search Attributes

### ISSUE THREAD

**Issue by roxblnfk** [temporalio/roadrunner-temporal#596]
### Plugin

Temporal

### I have an idea!

When starting a Child Workflow, we can pass SearchAttributes in the `ExecuteChildWorkflow` command.
SA are packed into a regular array as JSON within the [`options`](https://github.com/roadrunner-server/api/blob/bc182ac9dfac3acf730bbeb50ea36e29a7694cb8/proto/temporal/v1/temporal.proto#L25) field.

We need to add support for TypedSearchAttributes and allow passing SearchAttributes as protobuf.

Related issue: https://github.com/temporalio/sdk-php/issues/516

**Comment by rustatian** [comment]
Moved: https://github.com/roadrunner-server/roadrunner/issues/2097
