### ISSUE TITLE
[Bug] 60 seconds rescheduling time when processing many workfows at once

### ISSUE THREAD

**Issue by Rastusik** [temporalio/roadrunner-temporal#73]
**Describe the bug**
When load testing Temporal with php-sdk, the behaviour of the roadrunner workers is sometimes (I wasn't able to specify the conditions) weird - the processing will get stuck for 60 seconds and resume afterwards. Which is not ideal in a production deployment, when the processing gets paused for 60 seconds. When running multiple roadrunner processes at once (each with multiple workers), the processing won't get stuck, or at least, not all the roadrunner instances get stuck, so the chance of this to happen are much lower. It seems like there is a timeout in roadrunner. 

**To Reproduce**
I was also able to reproduce the behaviour on a modified sample from the samples repository (https://github.com/temporalio/samples-php)

I am running the polymorhpic example but I modified the ExecuteCommand to this:
```
class ExecuteCommand extends Command
{
    protected const NAME = 'polymorphic';
    protected const DESCRIPTION = 'Execute PolymorphicActivity\GreetingWorkflow';

    public function execute(InputInterface $input, OutputInterface $output)
    {


        $output->writeln("Starting <comment>GreetingWorkflow</comment>... ");

        for ($i = 0; $i < 2000; $i++) {
            $workflow = $this->workflowClient->newWorkflowStub(
                GreetingWorkflowInterface::class,
                WorkflowOptions::new()//->withWorkflowExecutionTimeout(CarbonInterval::minute())
            );
            $run = $this->workflowClient->start($workflow, 'Antony');
        }
//        $output->writeln(
//            sprintf(
//                'Started: WorkflowID=<fg=magenta>%s</fg=magenta>, RunID=<fg=magenta>%s</fg=magenta>',
//                $run->getExecution()->getID(),
//                $run->getExecution()->getRunID(),
//            )
//        );
//
//        $output->writeln(sprintf("Result:\n<info>%s</info>", $run->getResult()));

        return self::SUCCESS;
    }
}
```

and the GreetingWorkflow to this:
```
class GreetingWorkflow implements GreetingWorkflowInterface
{
    /** @var GreetingWorkflowInterface[] */
    private $greetingActivities = [];

    public function __construct()
    {
        $this->greetingActivities = [
            Workflow::newActivityStub(
                HelloActivity::class,
                ActivityOptions::new()->withScheduleToCloseTimeout(CarbonInterval::seconds(20))
            ),
            Workflow::newActivityStub(
                ByeActivity::class,
                ActivityOptions::new()->withScheduleToCloseTimeout(CarbonInterval::seconds(20))
            ),
        ];
    }

    public function greet(string $name): \Generator
    {
        $result = [];
        foreach ($this->greetingActivities as $activity) {
            $result[] = yield $activity->composeGreeting($name);
        }

        return join("\n", $result);
    }
}
```

It doesn't occur always but running multiple times after each other should make the problem appear

**Expected behavior**
When there are running workflows in Temporal scheduled for current time, the workers shouldn't be waiting, they should be processing them.

**Screenshots/Terminal ouput**
If applicable, add screenshots or code blocks to help explain your problem. You can also use [Loom](http://loom.com/) to do short, free video bug reports.

**Versions (please complete the following information where relevant):**
 - OS: Ubuntu in Docker for Mac
 - Temporal Version 1.10.1
 - are you using Docker or Kubernetes or building Temporal from source? Docker

**Additional context**
More detailed info is here: https://community.temporal.io/t/php-weird-behaviour-while-load-testing/2437/14

**Comment by rustatian** [comment]
@Rastusik Hey. As I promised, could you please try `v1.0.8-beta.1` ?

**Comment by Rastusik** [comment]
@rustatian Great! Thank you very much! Sure, I'm on it!

**Comment by Rastusik** [comment]
@rustatian es there any readme how to build the beta plugin with roadrunner? I've never done it before and would like to save some time.

**Comment by rustatian** [comment]
@Rastusik ah, ok, got u. Let me create a beta build for you (roadrunner-binary). give me a second.

**Comment by rustatian** [comment]
@Rastusik here you are: https://github.com/spiral/roadrunner-binary/releases/tag/v2.3.1-beta.5 (wait a few seconds until GitHub generates images)

**Comment by Rastusik** [comment]
@rustatian thanks for the build, I'm trying to test it for the last two hours but the whole thing behaves non-deterministically ... It looks like it runs better than before the change and there are less delays, but the delays still occur... sometimes more often, sometimes not ... 

It's hard to describe but it feels like when there are not enough free workers, that the workflows are being rescheduled 60 seconds later ... because sometimes when I start with one RR process and when stuck, I start running other ones, sometimes they get stuck too and sometimes not (which would mean that the workflows weren't rescheduled in these cases) ... this is the non-deterministic part ...

But when there are 3 RR processes from the beginning (10 workers each), there are no delays ...

**Comment by rustatian** [comment]
Did you setup an external (I mean, not in the docker) temporal server?

**Comment by Rastusik** [comment]
well, on the external deployment things seem to work (but I'm connecting from Slovakia to Ireland, so latencies may influence something)... I have to do some more tests tomorrow to confirm

**Comment by Rastusik** [comment]
@rustatian Ok, so I've made another round of tests today and the results are weird I can still hit use cases where delays occur. It can be seen in RR logs:

```
2021/06/25 15:02:28     DEBUG   temporal        ExecuteActivity {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::handle", "WorkflowID": "de40939b-3b6e-4280-89df-55bbaf8ac658_1", "RunID": "0625b18e-89d3-42c3-bc47-da3cd8ac62a9", "Attempt": 1, "ActivityID": "5", "ActivityType": "handle"}
2021/06/25 15:02:28     DEBUG   temporal        ExecuteChildWorkflow    {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::fork", "WorkflowID": "faad7b5d-18f4-4df2-a140-0a52364638e1", "RunID": "c9f987bc-818e-41a3-a883-f1791edaecbf", "Attempt": 1, "ChildWorkflowID": "c9f987bc-818e-41a3-a883-f1791edaecbf_1", "WorkflowType": "EventBus::handle"}
2021/06/25 15:02:29     DEBUG   temporal        ExecuteActivity {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::handle", "WorkflowID": "c42385b1-4f4a-45b8-a58f-967b32ba5cf9_1", "RunID": "0cf052a1-8ffb-42e4-8fd1-1bc7a24d2cf3", "Attempt": 1, "ActivityID": "5", "ActivityType": "handle"}
2021/06/25 15:02:29     DEBUG   temporal        ExecuteChildWorkflow    {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "Workflo
2021/06/25 15:02:29     DEBUG   temporal        ExecuteChildWorkflow    {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::fork", "WorkflowID": "feadf516-37ea-4ce8-a891-2d47b18fb495", "RunID": "0265fa2d-b368-4cc8-8c27-cbca64a31e9b", "Attempt": 1, "ChildWorkflowID": "0265fa2d-b368-4cc8-8c27-cbca64a31e9b_1", "WorkflowType": "EventBus::handle"}
2021/06/25 15:03:29     DEBUG   temporal        ExecuteChildWorkflow    {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::fork", "WorkflowID": "ad8d2c6f-f1b6-4ef0-98a3-7d1b72503cfa", "RunID": "3b845640-8347-4d73-b3d1-285de47805b3", "Attempt": 1, "ChildWorkflowID": "3b845640-8347-4d73-b3d1-285de47805b3_1", "WorkflowType": "EventBus::handle"}
2021/06/25 15:03:29     DEBUG   temporal        ExecuteActivity {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::handle", "WorkflowID": "297213b0-3ba8-4ac6-88b1-163fc693f543_1", "RunID": "dc376cb3-152a-4a57-a3e0-c9656f602093", "Attempt": 1, "ActivityID": "5", "ActivityType": "handle"}
2021/06/25 15:03:29     DEBUG   temporal        ExecuteChildWorkflow    {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::fork", "WorkflowID": "9e36d297-5802-446e-ae57-bd67be479f91", "RunID": "7f9d9461-c5c7-4777-9c42-4d73b220e5c7", "Attempt": 1, "ChildWorkflowID": "7f9d9461-c5c7-4777-9c42-4d73b220e5c7_1", "WorkflowType": "EventBus::handle"}
2021/06/25 15:03:29     DEBUG   temporal        ExecuteActivity {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::handle", "WorkflowID": "683b5b15-da88-4ce7-9ebd-4e82eaef7264_1", "RunID": "0d74a0c0-a9d8-44a3-92c5-64e2f1221de3", "Attempt": 1, "ActivityID": "5", "ActivityType": "handle"}
2021/06/25 15:03:29     DEBUG   tempor
2021/06/25 15:04:34     DEBUG   temporal        ExecuteActivity {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::handle", "WorkflowID": "81b90c4b-1493-478d-a037-5a042690ce34_1", "RunID": "538d8fa6-1de3-4e68-9d79-cb41ac05b722", "Attempt": 1, "ActivityID": "5", "ActivityType": "handle"}
2021/06/25 15:04:34     DEBUG   temporal        ExecuteChildWorkflow    {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::fork", "WorkflowID": "b27eabdd-7562-4068-9d54-30d38805fa6f", "RunID": "e42de207-b0be-45b5-94db-63a040b58485", "Attempt": 1, "ChildWorkflowID": "e42de207-b0be-45b5-94db-63a040b58485_1", "WorkflowType": "EventBus::handle"}
2021/06/25 15:04:34     DEBUG   temporal        ExecuteActivity {"Namespace": "eventbus", "TaskQueue": "default", "WorkerID": "10739@59b9dcda7abc@default@1", "WorkflowType": "EventBus::handle", "WorkflowID": "eb67fe2a-cccc-4862-8211-47ce44d0a357_1", "RunID": "f304586c-5818-4833-a239-cc125e8f4528", "Attempt": 1, "ActivityID": "5", "ActivityType": "handle"}
```

In the snipped there are entries occurring at 15:02:29, then there is a wait and the next entry is at 15:03:29 ... similarly at 15:04:34 ... (tho entries are truncated, there are a couple more in reality)

I'm testing with temporal deployment in kubernetes (from official charts, with aurora/mysql and elastic).

I thought that this correlates with my workflow code, but it isn't blocking anywhere... One correlation was when I was using child workfows in a workflow - with that the problem occurred every time.... when I switched the child workflows to activities (just as an experiment), everything worked ... 

Funny thing is that when the workers are stuck and I start the second or third RR process, everything works... the new processes are behaving correctly most of the time, but once in a time get they get stuck too, but meanwhile the other ones get un-stuck... 

I am not 100% sure but I think that the patch made an improvement (I'm not able to measure it though), before the delays occurred a little bit more often ... Is there any possibility that there still is some timeout forgotten somewhere?

**Comment by wolfy-j** [comment]
I'm currently waiting for an access to the production grace cluster to test it out. We are planning to improve worker structure in 1.1 anyway, but I think it worth investigating at the moment.

Do you have any metrics about the Temporal server itself? Is it overloaded or something? Can we isolate the use-case with child workflows vs activities. Are you clearly NOT getting such issues with Activities?

@rustatian do we have any other timeouts at the workflow process level? I don't think so...

**Comment by wolfy-j** [comment]
Wow! Thank you very much for so many details. 

The ChildWorkflow use-case has a very specific flow cos we have to allocate workflow and then wait for the start. So we might have a bug somewhere in this mix rather than the whole processing pipeline. 

In our benches, we did not use the example of ChildWorkflows as we expected it to be redundant. So now we have a clear direction where to dig.

The rest of the pipeline should be OK and we benched it.

**Comment by Rastusik** [comment]
@wolfy-j no problem, I'm highly motivated to get this into production, so thank you for looking into it :) ...

regarding the options in constructor, I know that there is the way you are mentioning, but I've done it like it is for a specific reason - the options configuration data are coming in from the input data structure and may be specific for each handler definition

**Comment by wolfy-j** [comment]
Yeah, that makes sense.

**Comment by Rastusik** [comment]
Hey @wolfy-j would it be possible to publish your load test code? I would try to rule out our temporal setup with it.. 

Maybe I'm doing something wrong in the code but the delays occurred again even when multiple pods with roadrunner are running

**Comment by wolfy-j** [comment]
Unfortunately, I can not share the benchmark setup. Are you talking still about the issue with Child Workflows or it's about another use case?

**Comment by wolfy-j** [comment]
FYI, we are working on the 1.1 milestone where we are going to change the way how workers defined on the Golang side. It should provide extra bits of performance and better scalabiltiy.

**Comment by Rastusik** [comment]
Oh, sorry to hear that, but I understand. Well, it seems that the problem occurs also without child workflows. I have created a custom metric, a counter for processed activities and the charts show, that there are delays event with multiple RR pods.

<img width="2136" alt="Screenshot 2021-07-02 at 10 01 53" src="https://user-images.githubusercontent.com/1735097/124242076-a6dcfd80-db1c-11eb-9a6b-c6086ebb3918.png">

Each activity is generating two other workflows so there shouldn't be any delays IMHO...

**Comment by Rastusik** [comment]
Maybe one more question, are you using the original grafana  charts for temporal? I found some information in the docs that for performance tests, one should be watching the `ScheduleToStart` latency in the charts but I don't see it anywhere

**Comment by wolfy-j** [comment]
Not really, we are using throughput metrics. Not so detailed as yours, but I'll check how we can add more visibility to them.

I need some time to dig into the setup.

**Comment by wolfy-j** [comment]
@rustatian I wonder if we should expose some of the temporal worker metrics from RR. It should help to debug such issues.

**Comment by wolfy-j** [comment]
@Rastusik are you OK to use our custom build, just in case, so we can snapshot metrics from the RR side?

**Comment by Rastusik** [comment]
@wolfy-j sure, I'd love to do it! There is still lack of visibility in the whole proces for me

**Comment by wolfy-j** [comment]
Is it possible for you to share the whole setup with us? The worker setup and workflows you use.

I apologize for the inconvenience, it's pretty complex system, we will try to expose more metrics going forward.

**Comment by Rastusik** [comment]
sure, but I would prefer to use a private channel for that, do you have any idea how to get the code to you?

**Comment by wolfy-j** [comment]
Can you ping me by email? wolfy.jd@gmail.com

**Comment by Rastusik** [comment]
sure, I just sent it. thanks a lot for looking into it

**Comment by wolfy-j** [comment]
The timeout is related to the socket issues between Golang SDK and the Temporal server. We did internal benchmarks and found no issues related to the PHP SDK or RoadRunner code. I would recommend asking about such behavior on the main channel.

Also, make sure to set proper values for MaxWorkflowPollers to avoid oversaturation.

**Comment by Rastusik** [comment]
so according to this advice from private conversation:
```
Also, by looking at your code you did not set up any polling limits which might create a ton of extra connections. 
\Temporal\Worker\WorkerOptions::new()
    ->withMaxConcurrentActivityTaskPollers(8)
    ->withMaxConcurrentWorkflowTaskPollers(4)
You can try to limit it by doing this (set the first number by the number of your workers, and the second by the number of your shards).

In 1.1 we will make these parameters to control actual worker pool size.
```

After setting the parameters, the behaviour stopped and everything works as expected, thank you very much! :)

I think the parameters should be definitely mentioned in the documentation. TBH I didn’t really understand what the correct setting should be - in the code comments, the information has only general character.

From what you were writing, I didn’t understand completely what you mean:

```
You can try to limit it by doing this (set the first (activity pollers) number by the number of your workers, and the second (workflow pollers)  by the number of your shards).
```

@wolfy-j 
Regarding the activity pollers: which workers did you mean? I suppose that you meant RR workers, but would like to be sure.
Regarding the workflow pollers: did you mean the number of history shards? because that didn’t work, we have 512 history shards in our setup and the delays were occurring when having 8 activity pollers and 512 workflow pollers…

My current working setting is 8 activity pollers and 8 workflow pollers and the system is stable. But I have no idea what these numbers mean, I haven’t googled it yet, if the information is generally available, I’ll find it, but I’ll be thankful for any additional information.

thanks again, the initial problem is solved with the worker options :)

**Comment by tsurdilo** [comment]
> I think the parameters should be definitely mentioned in the documentation.

Definitely. Will work on adding it!
