### ISSUE TITLE
[BUG] Roadrunner starts with 2 temporal workers even if in config i set more

### ISSUE THREAD

**Issue by mixadior** [temporalio/roadrunner-temporal#80]
### Describe the bug

I set in .rr.yaml file `temporal.activities.num_workers` to `4` , but when i start `rr` i see only 2 workers running.

### To Reproduce

1. build docker container https://github.com/temporalio/samples-php/blob/master/Dockerfile 
2. i took code from here (https://github.com/wolfy-j/temporal-workshop) and mounted it in docker volume in `/var/app/workshop`
3. ran container in interactive mode with bash (docker run -v /Volumes/Workspace/projects/temporal-workshop/temporal-workshop:/var/app/workshop -it temporal-php-samples bash)
4. started rr with `rr serve -c /var/app/workshop/.rr.yaml -w /var/app/workshop` and see such result:

```
root@2e358f6cd379:/var/app/workshop# rr serve -w . -c ./.rr.yaml
2021/08/16 18:22:06	INFO	temporal    	Started Worker	{"Namespace": "default", "TaskQueue": "default", "WorkerID": "12560@2e358f6cd379@default@1"}
2021/08/16 18:22:09	INFO	temporal    	Started Worker	{"Namespace": "default", "TaskQueue": "default", "WorkerID": "12560@2e358f6cd379@default@2"}
```

### Expected behavior

expected to see 4 workers running, because in config it's  `temporal.activities.num_workers` = `4`

### Versions

- Host OS: MacOS
- Temporal Version: 1.11.2
- Temporal docker-compose from here https://github.com/temporalio/docker-compose

### Additional context

nope

**Comment by rustatian** [comment]
Hey @mixadior, nice to meet you. You are using the wrong comments. You see the `workflow` worker (`INFO ...`) here. But to see all workers, `workflow` and `activities` you should build the RR and use `./rr workers -i -c .rr.yaml` command.  You can't combine `-w` with `serve`.

**Comment by rustatian** [comment]
Keep in mind, that `roadrunner-temporal` at the moment uses 1 workflow worker and a configurable number of the `activities` workers.

**Comment by mixadior** [comment]
Hi, thx for fast response.

>  You are using the wrong command. You see the workflow worker (INFO ...) here.

but i see 2 workers started, even when i restarted rr with `-w` option only: 

```
root@08f2e54dd0aa:/var/app/workshop# rr serve -w /var/app/workshop/
2021/08/18 11:09:28	INFO	temporal    	Started Worker	{"Namespace": "default", "TaskQueue": "default", "WorkerID": "1151@08f2e54dd0aa@default@1"}
2021/08/18 11:09:31	INFO	temporal    	Started Worker	{"Namespace": "default", "TaskQueue": "default", "WorkerID": "1151@08f2e54dd0aa@default@2"}
```

when i stop `rr` i see 2 workers stopping. Roadrunner version:

```
root@08f2e54dd0aa:/var/app/workshop# rr -v
rr version 2.3.3 (build time: 2021-07-14T15:29:03+0000, go1.16.4)
```

> But to see all workers, workflow and activities you should build the RR and use ./rr workers -i -c .rr.yaml

i see here only http workers, even when rr is processing some temporal activities:

http://feodosian.com/public/guake_com.docker.cli_2021-08-18_14-15-06.png

no temporal workers.

**Comment by rustatian** [comment]
Hey, `-w` here doesn't mean `worker(s)`, it means - `working dir`. So, it's totally fine to use it with the directory. Could you please show your `.rr.yaml` ?

**Comment by rustatian** [comment]
I found a little issue, which prevents `temporal` plugin to see info about processes. I'll add this bug to the current sprint. After fix you'll see, that everything is fine:
![image](https://user-images.githubusercontent.com/8040338/129896023-93c15ec6-c74a-4f6b-aa10-f5f06beb9a6a.png)

These two workers, which you see in the logs are temporal workers to handle `workflows` and `activities` attached to our own pool with workers. 1 temporal worker to handle workflows (workflow worker), 1 temporal worker to handle activities connected to our workers' pool which you can configure via `.rr.yaml`.

**Comment by mixadior** [comment]
My .rr.yaml

```
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"
  env:
    XDEBUG_SESSION: 1
    XDEBUG_CONFIG: idekey=PHPSTORM
    PHP_IDE_CONFIG: serverName=temporalphp
    

logs:
  level: info
  channels:
    informer.mode: none

temporal:
  address: host.docker.internal:7233
  activities:
    debug: false
    num_workers: 8

http:
  address: 127.0.0.1:8080
  pool:
    num_workers: 8

```

**Comment by rustatian** [comment]
Ok, I am going to close this issue and open the new one related to the absent information about workers. You can check the correct number of activities by executing: `ps aux | grep "php worker.php"`.

**Comment by rustatian** [comment]
ref: #81
